/**
 * PG_RFQ_SPEC.md §6 시나리오 A — 구매사 RFQ 발송.
 *
 * Buyer logs in, creates a new RFQ, supplies allowed PG emails (3),
 * submits, lands on the RFQ detail page. Verifies:
 *   - rfqs row inserted with status='sent'
 *   - rfq_invitations × 3 (one per PG email)
 *   - outbox_entries × 4 (1 rfq.sent + 3 rfq.invited)
 *   - UI: comparison table shows 0 bids
 *
 * State: globalSetup truncated + reseeded the test DB. Buyer
 * `yeonseong.dev@gmail.com` has bizProfile with bizNo `123-45-67890`
 * and grade `sme2`. We do NOT touch the seeded `Q-2604-0001` RFQ —
 * scenario A creates a fresh one whose ID is auto-generated by
 * `nextRfqId()` (YYMM + seq).
 */
import { test, expect } from 'playwright/test';
import { sql } from 'drizzle-orm';
import { db } from '@/lib/db/client';

// Force the DB client to point at the test DB before importing it.
// playwright globalSetup already set this in the parent process; this
// ensures any worker that re-imports the module also uses the test URL.
process.env.DATABASE_URL =
  process.env.DATABASE_URL_TEST ??
  'postgres://bidit:bidit@localhost:5433/bidit_test';

const BUYER_EMAIL = 'yeonseong.dev@gmail.com';
const BUYER_PASSWORD = 'password123';

test.describe.serial('Scenario A — buyer creates and sends RFQ', () => {
  test('buyer logs in, creates RFQ, sends to 3 PGs, lands on detail page', async ({
    page,
  }) => {
    // ── 1. Login ─────────────────────────────────────────────────
    await page.goto('/login');
    await page.fill('input[name="email"]', BUYER_EMAIL);
    await page.fill('input[name="password"]', BUYER_PASSWORD);
    await page.getByRole('button', { name: '로그인' }).click();
    await expect(page).toHaveURL(/\/home$/, { timeout: 15_000 });

    // ── 2. Open the new-RFQ form ─────────────────────────────────
    await page.goto('/rfq/new');
    await expect(page.getByText('신규 견적 요청')).toBeVisible();
    // Workspace bizProfile (123-45-67890) and grade (sme2) are rendered
    // by the RSC parent — verify the page didn't redirect to "missing
    // workspace bizProfile" branch.
    await expect(page.getByText('123-45-67890')).toBeVisible();

    // ── 3. Fill form fields ──────────────────────────────────────
    // Title input — only text input on the form (memo is textarea).
    await page
      .getByPlaceholder('2026 결제 인프라 견적')
      .fill('e2e-A-2026 결제 인프라 견적');
    await page
      .getByPlaceholder(/카드결제·간편결제 통합 솔루션 검토 중입니다/)
      .fill('e2e scenario A — automated send');

    // Allowed PG emails: type each, press Enter to commit chip.
    const pgEmails = [
      'sales@toss.im',
      'biz@inicis.com',
      'partner@kakaopay.com',
    ];
    const emailField = page.getByPlaceholder(/sales@/);
    for (const email of pgEmails) {
      await emailField.fill(email);
      await emailField.press('Enter');
    }

    // ── 4. Submit ────────────────────────────────────────────────
    // Button text reflects count: "3개 PG사에 발송"
    await page.getByRole('button', { name: /3개 PG사에 발송|발송/ }).click();

    // ── 5. Land on /rfq/<rfqId> ──────────────────────────────────
    await page.waitForURL(/\/rfq\/Q-\d{4}-\d{4}$/, { timeout: 15_000 });
    const url = new URL(page.url());
    const rfqId = url.pathname.split('/').pop()!;
    expect(rfqId).toMatch(/^Q-\d{4}-\d{4}$/);

    // Comparison table shows zero bids since no PG has submitted.
    // BidComparisonTable renders an EmptyState with this exact copy when
    // bids.length === 0 (see components/rfq/BidComparisonTable.tsx).
    await expect(
      page.getByText('아직 받은 견적이 없습니다.'),
    ).toBeVisible({ timeout: 10_000 });

    // ── 6. DB assertions ─────────────────────────────────────────
    const rfqRows = await db.execute<{ id: string; status: string }>(
      sql`SELECT id, status FROM rfqs WHERE id = ${rfqId}`,
    );
    const rfqArr = Array.isArray(rfqRows)
      ? rfqRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((rfqRows as any).rows ?? []);
    expect(rfqArr).toHaveLength(1);
    expect(rfqArr[0].status).toBe('sent');

    const inviteRows = await db.execute<{ c: number }>(
      sql`SELECT count(*)::int AS c FROM rfq_invitations WHERE rfq_id = ${rfqId}`,
    );
    const inviteArr = Array.isArray(inviteRows)
      ? inviteRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((inviteRows as any).rows ?? []);
    expect(inviteArr[0].c).toBe(3);

    // Outbox: 1 rfq.sent + 3 rfq.invited = 4 entries scoped to this RFQ.
    // The outbox payload references rfqId in its JSONB; we filter by
    // event_type to keep the assertion precise.
    const outboxRows = await db.execute<{ c: number }>(
      sql`SELECT count(*)::int AS c FROM outbox_entries
          WHERE event_type IN ('rfq.sent', 'rfq.invited')
            AND payload->>'rfqId' = ${rfqId}`,
    );
    const outboxArr = Array.isArray(outboxRows)
      ? outboxRows
      : // eslint-disable-next-line @typescript-eslint/no-explicit-any
        ((outboxRows as any).rows ?? []);
    expect(outboxArr[0].c).toBe(4);
  });
});
